name: Testes Aula 10

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Testar IMC
        working-directory: aula10devops
        run: mvn test

      - name: Testar Potencia
        working-directory: aula10potencia
        run: mvn test